import { StyleSheet } from 'react-native';

export const WatchAdsScreenStyles = StyleSheet.create({
  background: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
  content: {
    padding: 24,
    paddingTop: 60,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 24,
    paddingTop: 30,
    paddingHorizontal: 15,
    marginLeft: 145,
    position: 'relative',
  },
  headerCenter: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 187, 0, 0.2)',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#ffb300',
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginLeft: -30,
    marginTop: -25
  },
  headerTitle: {
    color: '#ffdd77',
    fontSize: 15,
    fontWeight: '600',
    marginLeft: 8,
  },
  cancelButton: {
    position: 'absolute',
    right: -10,
    // top: 10,
    padding: 5,
    zIndex: 999,
  },
  cancelButtonImage: {
    width: 50,
    height: 50,
  },
  rewardCard: {
    width: '122%',
    overflow: 'hidden',
    padding: 68,
    marginTop: -10,
    marginLeft: -35,
  },
  cardImageStyle: {
    resizeMode: 'cover',
    borderRadius: 16,

  },
  cardContent: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: -15,
    marginLeft: -35,
  },
  cardTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#f0bb7bff',
    marginTop: 8,
    marginBottom: 4,
  },
  cardDescription: {
    fontSize: 12,
    color: '#e2b263ff',
    textAlign: 'center',
    marginBottom: 16,
    paddingHorizontal: 20,
  },
  rewardOptions: {
    width: '100%',
    alignItems: 'center',
    marginTop: 0,
  },
  rewardLabel: {
    fontSize: 14,
    color: '#d6b58c',
    marginBottom: 8,
    fontWeight: '600',
  },
  tokenRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 10,
    marginBottom: 10,
  },
  tokenBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(251, 191, 36, 0.1)',
    paddingHorizontal: 30,
    paddingVertical: 7,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(251, 191, 36, 0.3)',
    gap: 5,
  },
  tokenText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#fbbf24',
  },
  watchButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 170, 0, 0.15)',
    paddingVertical: 18,
    paddingHorizontal: 24,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: '#ffaa00b5',
    marginBottom: 24,
    gap: 12,
  },
  watchButtonDisabled: {
    opacity: 0.5,
  },
  watchButtonText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#ffaa00b5',
  },
  infoSection: {
    backgroundColor: 'rgba(214, 181, 140, 0.1)',
    padding: 20,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(214, 181, 140, 0.2)',
    marginBottom: 24,
  },
  infoTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#d79749ff',
    marginBottom: 12,
  },
  infoText: {
    fontSize: 14,
    color: '#bd9b68ff',
    lineHeight: 22,
  },
  successCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 215, 0, 0.12)',
    padding: 20,
    borderRadius: 24,
    borderWidth: 2,
    borderStyle: 'dashed',
    borderColor: '#ffd700',
    gap: 14,
  },
  successText: {
    fontSize: 17,
    fontWeight: '800',
    color: '#ffd700',
    letterSpacing: 0.5,
    textShadowColor: 'rgba(255, 215, 0, 0.3)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  noAdsCard: {
    backgroundColor: 'rgba(214, 181, 140, 0.15)',
    padding: 24,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: 'rgba(214, 181, 140, 0.3)',
    marginBottom: 24,
    alignItems: 'center',
  },
  noAdsTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#d6b58c',
    marginBottom: 12,
    textAlign: 'center',
  },
  noAdsText: {
    fontSize: 14,
    color: '#a0a0a0',
    textAlign: 'center',
    marginBottom: 16,
    lineHeight: 20,
  },
  retryButton: {
    backgroundColor: 'rgba(255, 170, 0, 0.2)',
    paddingVertical: 12,
    paddingHorizontal: 32,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#ffaa00b5',
  },
  retryButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#ffaa00b5',
  },
});
